# Generated by Django 4.2 on 2023-09-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_spaces', models.IntegerField(default=15)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_registration', models.CharField(max_length=15)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('size', models.FloatField(blank=True)),
                ('KMs_for_liter', models.FloatField(blank=True)),
            ],
        ),
    ]
